### ISSUE TITLE
Can't create VM

### ISSUE THREAD

**Issue by dksh** [test-kitchen/kitchen-openstack#160]
Hi,

I tried following the README to create a VM but got the following error:

```
$ kitchen create
-----> Starting Kitchen (v1.15.0)
-----> Creating <default-centos-73>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Create failed on instance <default-centos-73>.  Please see .kitchen/logs/default-centos-73.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

```
Am I missing some required config?
Details below.

Here are the contents of .kitchen/logs/default-centos-73.log
```
$ cat .kitchen/logs/default-centos-73.log
I, [2017-03-15T11:26:43.647613 #10202]  INFO -- default-centos-73: -----> Creating <default-centos-73>...
E, [2017-03-15T11:26:43.781454 #10202] ERROR -- default-centos-73: Create failed on instance <default-centos-73>.
E, [2017-03-15T11:26:43.781635 #10202] ERROR -- default-centos-73: ------Exception-------
E, [2017-03-15T11:26:43.781674 #10202] ERROR -- default-centos-73: Class: Kitchen::ActionFailed
E, [2017-03-15T11:26:43.781733 #10202] ERROR -- default-centos-73: Message: Expected([201]) <=> Actual(400 Bad Request)
excon.error.response
  :body          => "{\"error\": {\"message\": \"get_version_v3() got an unexpected keyword argument 'auth'\", \"code\": 400, \"title\": \"Bad Request\"}}"
  :cookies       => [
  ]
  :headers       => {
    "Connection"             => "close"
    "Content-Length"         => "121"
    "Content-Type"           => "application/json"
    "Date"                   => "Wed, 15 Mar 2017 02:26:43 GMT"
    "Server"                 => "Apache/2.4.7 (Ubuntu)"
    "Vary"                   => "X-Auth-Token"
    "X-Distribution"         => "Ubuntu"
    "x-openstack-request-id" => "req-3d97f8ac-3e89-49cb-99d0-10ed07372b01"
  }
  :host          => "my-openstack-liberty"
  :local_address => "my-ip"
  :local_port    => 52722
  :path          => "/v3"
  :port          => 5000
  :reason_phrase => "Bad Request"
  :remote_ip     => "openstack-ip"
  :status        => 400
  :status_line   => "HTTP/1.1 400 Bad Request\r\n"

E, [2017-03-15T11:26:43.781762 #10202] ERROR -- default-centos-73: ----------------------
E, [2017-03-15T11:26:43.781785 #10202] ERROR -- default-centos-73: ------Backtrace-------
E, [2017-03-15T11:26:43.781807 #10202] ERROR -- default-centos-73: ~/.chefdk/gem/ruby/2.3.0/gems/kitchen-openstack-3.3.0/lib/kitchen/driver/openstack.rb:101:in `rescue in create'
E, [2017-03-15T11:26:43.781832 #10202] ERROR -- default-centos-73: ~/.chefdk/gem/ruby/2.3.0/gems/kitchen-openstack-3.3.0/lib/kitchen/driver/openstack.rb:75:in `create'
E, [2017-03-15T11:26:43.781858 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:460:in `public_send'
E, [2017-03-15T11:26:43.781882 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:460:in `block in perform_action'
E, [2017-03-15T11:26:43.781905 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-03-15T11:26:43.781927 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2017-03-15T11:26:43.781950 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-03-15T11:26:43.781973 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:488:in `action'
E, [2017-03-15T11:26:43.781996 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:460:in `perform_action'
E, [2017-03-15T11:26:43.782019 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:370:in `create_action'
E, [2017-03-15T11:26:43.782042 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-03-15T11:26:43.782068 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:358:in `each'
E, [2017-03-15T11:26:43.782093 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2017-03-15T11:26:43.782116 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:124:in `create'
E, [2017-03-15T11:26:43.782152 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:197:in `public_send'
E, [2017-03-15T11:26:43.782180 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-03-15T11:26:43.782203 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-03-15T11:26:43.782226 #10202] ERROR -- default-centos-73: ----End Backtrace-----
E, [2017-03-15T11:26:43.782248 #10202] ERROR -- default-centos-73: ---Nested Exception---
E, [2017-03-15T11:26:43.782270 #10202] ERROR -- default-centos-73: Class: Excon::Error::BadRequest
E, [2017-03-15T11:26:43.782291 #10202] ERROR -- default-centos-73: Message: Expected([201]) <=> Actual(400 Bad Request)
excon.error.response
  :body          => "{\"error\": {\"message\": \"get_version_v3() got an unexpected keyword argument 'auth'\", \"code\": 400, \"title\": \"Bad Request\"}}"
  :cookies       => [
  ]
  :headers       => {
    "Connection"             => "close"
    "Content-Length"         => "121"
    "Content-Type"           => "application/json"
    "Date"                   => "Wed, 15 Mar 2017 02:26:43 GMT"
    "Server"                 => "Apache/2.4.7 (Ubuntu)"
    "Vary"                   => "X-Auth-Token"
    "X-Distribution"         => "Ubuntu"
    "x-openstack-request-id" => "req-3d97f8ac-3e89-49cb-99d0-10ed07372b01"
  }
  :host          => "my-openstack-liberty"
  :local_address => "my-ip"
  :local_port    => 52722
  :path          => "/v3"
  :port          => 5000
  :reason_phrase => "Bad Request"
  :remote_ip     => "openstack-ip"
  :status        => 400
  :status_line   => "HTTP/1.1 400 Bad Request\r\n"

E, [2017-03-15T11:26:43.782318 #10202] ERROR -- default-centos-73: ----------------------
E, [2017-03-15T11:26:43.782342 #10202] ERROR -- default-centos-73: ------Backtrace-------
E, [2017-03-15T11:26:43.782364 #10202] ERROR -- default-centos-73: ~/.chefdk/gem/ruby/2.3.0/gems/kitchen-openstack-3.3.0/lib/kitchen/driver/openstack.rb:101:in `rescue in create'
E, [2017-03-15T11:26:43.782385 #10202] ERROR -- default-centos-73: ~/.chefdk/gem/ruby/2.3.0/gems/kitchen-openstack-3.3.0/lib/kitchen/driver/openstack.rb:75:in `create'
E, [2017-03-15T11:26:43.782408 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:460:in `public_send'
E, [2017-03-15T11:26:43.782447 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:460:in `block in perform_action'
E, [2017-03-15T11:26:43.782476 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-03-15T11:26:43.782500 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2017-03-15T11:26:43.782523 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-03-15T11:26:43.782545 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:488:in `action'
E, [2017-03-15T11:26:43.782568 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:460:in `perform_action'
E, [2017-03-15T11:26:43.782590 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:370:in `create_action'
E, [2017-03-15T11:26:43.782613 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-03-15T11:26:43.782642 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:358:in `each'
E, [2017-03-15T11:26:43.782668 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2017-03-15T11:26:43.782716 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:124:in `create'
E, [2017-03-15T11:26:43.782748 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:197:in `public_send'
E, [2017-03-15T11:26:43.782773 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-03-15T11:26:43.782795 #10202] ERROR -- default-centos-73: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-03-15T11:26:43.782818 #10202] ERROR -- default-centos-73: ----End Backtrace-----


```
Kitchen diagnosis:
```
$ kitchen diagnose --all
---
timestamp: 2017-03-15 02:29:50 UTC
kitchen_version: 1.15.0
plugins:
  driver:
    Openstack:
      class: Kitchen::Driver::Openstack
      version: 3.3.0
      api_version: 2
  provisioner:
    ChefZero:
      class: Kitchen::Provisioner::ChefZero
      version: 1.15.0
      api_version: 2
  transport:
    Ssh:
      class: Kitchen::Transport::Ssh
      version: 1.15.0
      api_version: 1
  verifier:
    Inspec:
      class: Kitchen::Verifier::Inspec
      version: 0.17.0
      api_version: 1
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config: 
  project_config:
    filename: "~/my-cookbook/.kitchen.yml"
    raw_data:
      driver:
        name: openstack
        openstack_username: my-username
        openstack_api_key: my-password
        openstack_auth_url: http://my-openstack-liberty:5000/v3
        require_chef_omnibus: true
        image_ref: my-centos73-image
        flavor_ref: my-flavor
        server_name: my-server
        openstack_project_name: my-project
        openstack_domain_name: default
        openstack_region: my-region
      transport:
        username: centos
      provisioner:
        name: chef_zero
        always_update_cookbooks: true
      verifier:
        name: inspec
      platforms:
      - name: centos-7.3
      suites:
      - name: default
        run_list:
        - recipe[my-cookbook::default]
        verifier:
          inspec_tests:
          - test/smoke/default
        attributes: 
  local_config: 
  combined_config:
    filename: 
    raw_data:
      driver:
        name: openstack
        openstack_username: my-username
        openstack_api_key: my-password
        openstack_auth_url: http://my-openstack-liberty:5000/v3
        require_chef_omnibus: true
        image_ref: my-centos73-image
        flavor_ref: my-favor
        server_name: my-server
        openstack_project_name: my-project
        openstack_domain_name: default
        openstack_region: my-region
      transport:
        username: centos
      provisioner:
        name: chef_zero
        always_update_cookbooks: true
      verifier:
        name: inspec
      platforms:
      - name: centos-7.3
      suites:
      - name: default
        run_list:
        - recipe[my-cookbook::default]
        verifier:
          inspec_tests:
          - test/smoke/default
        attributes: 
instances:
  default-centos-73:
    platform:
      os_type: unix
      shell_type: bourne
    state_file:
      last_error: Kitchen::ActionFailed
    driver:
      allocate_floating_ip: false
      availability_zone: 
      block_device_mapping: 
      connect_timeout: 60
      flavor_ref: standard-1-4
      floating_ip: 
      floating_ip_pool: 
      glance_cache_wait_timeout: 600
      image_ref: centos-7.3.1611-20161213
      key_name: 
      kitchen_root: "~/my-cookbook"
      log_level: :info
      name: openstack
      network_id: 
      network_ref: 
      no_ssh_tcp_check: false
      no_ssh_tcp_check_sleep: 120
      openstack_api_key: my-password
      openstack_auth_url: http://my-openstack-liberty:5000/v3
      openstack_domain_name: default
      openstack_network_name: 
      openstack_project_name: my-project
      openstack_region: my-region
      openstack_service_name: 
      openstack_tenant: 
      openstack_username: my-username
      port: '22'
      private_ip_order: 0
      public_ip_order: 0
      read_timeout: 60
      security_groups: 
      server_name: my-server
      server_name_prefix: 
      test_base_path: "~/my-cookbook/test/integration"
      use_ipv6: false
      write_timeout: 60
    provisioner:
      always_update_cookbooks: true
      attributes: {}
      chef_client_path: "/bin/chef-client"
      chef_omnibus_install_options: 
      chef_omnibus_url: https://omnitruck.chef.io/install.sh
      chef_zero_host: 
      chef_zero_port: 8889
      client_rb: {}
      clients_path: 
      command_prefix: 
      config_path: 
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path: 
      data_path: 
      deprecations_as_errors: false
      encrypted_data_bag_secret_key_path: 
      environments_path: 
      ftp_proxy: 
      http_proxy: 
      https_proxy: 
      json_attributes: true
      kitchen_root: "~/my-cookbook"
      log_file: 
      log_level: auto
      max_retries: 1
      name: chef_zero
      named_run_list: {}
      nodes_path: 
      policyfile: 
      policyfile_path: 
      profile_ruby: false
      require_chef_omnibus: true
      retry_on_exit_code: []
      roles_path: 
      root_path: "/tmp/kitchen"
      ruby_bindir: "/embedded/bin"
      run_list:
      - recipe[my-cookbook::default]
      sudo: true
      sudo_command: sudo -E
      test_base_path: "~/my-cookbook/test/integration"
      wait_for_retry: 30
    transport:
      compression: false
      compression_level: 0
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      kitchen_root: "~/my-cookbook"
      log_level: :info
      max_ssh_sessions: 9
      max_wait_until_ready: 600
      name: ssh
      port: 22
      ssh_gateway: 
      ssh_gateway_username: 
      ssh_key: 
      test_base_path: "~/my-cookbook/test/integration"
      username: centos
    verifier:
      chef_omnibus_root: "/opt/chef"
      command_prefix: 
      ftp_proxy: 
      http_proxy: 
      https_proxy: 
      inspec_tests:
      - test/smoke/default
      kitchen_root: "~/my-cookbook"
      log_level: :info
      name: inspec
      root_path: "/tmp/verifier"
      sudo: true
      sudo_command: sudo -E
      suite_name: default
      test_base_path: "~/my-cookbook/test/integration"
```

Config file:
```
$ cat .kitchen.yml 
---
driver:
  name: openstack
  openstack_username: my-username
  openstack_api_key: my-password
  openstack_auth_url: http://my-openstack-liberty:5000/v3
  require_chef_omnibus: true
  image_ref: my-centos73-image
  flavor_ref: my-flavor
  server_name: my-server
  openstack_project_name: my-project
  openstack_domain_name: default
  openstack_region: my-region
transport:
  username: centos

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[my-cookbook::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:

```

**Comment by dksh** [comment]
Found the problem.

I was accessing `API_URL/v3` but I the correct URI is `API_URL/v3/auth/tokens`

Wish there was better documentation :'(

Closing this issue

**Comment by jjasghar** [comment]
Would this be better? https://github.com/test-kitchen/kitchen-openstack/pull/161
