### ISSUE TITLE
Issue attaching an Floating IP from a Pool

### ISSUE THREAD

**Issue by B1Sandmann** [test-kitchen/kitchen-openstack#169]
When trying to run tests in our internal setup test-kitchen isn't able to get a floating IP from a pool of floating IPs. Instead I get an error that there are no floating IPs available in the pool but there are many IPs available. The external network however is a shared one as well as the internal one so it might behave different than a normal setup where external network, internal network and router are part of the project. It does however work with a fixed floating IP, but as we would like to run multiple tests in parallel the pool feature would be a huge help.

All this is with kitchen 1.16 and kitchen-openstack 3.1.4 and 3.1.5 as well.

The .kitchen.yml (slightly anonymized)
```
---
driver:
  name: openstack
driver_config:
  openstack_username: <%= ENV['OS_USERNAME'] %>
  openstack_api_key: <%= ENV['OS_PASSWORD']%> # AKA your OpenStack Password
  openstack_auth_url: <%= ENV['OS_AUTH_URL']%>/auth/tokens # needed because v3 usses a new address that the driver otherwise doesn't recongize
  openstack_domain_name: <%= ENV['OS_PROJECT_DOMAIN_NAME'] %>
  openstack_project_name: <%= ENV['OS_PROJECT_NAME'] %>
  openstack_region: <%= ENV['OS_REGION_NAME'] %>
  key_name: id_kitchen # name of the SSH Key used in Openstack, needs to be adjusted to the individual setup
  disable_ssl_validation: true # we need this for staging :(

  # these should be equal for all tests
  require_chef_omnibus: true # chef is responsible for installing the busser(test) so we should use omnibus
  flavor_ref: 20 # = m1.small flavor
  # 180 is suggested by the driver documentation, can be adjusted
  read_timeout: 180
  write_timeout: 180
  connect_timeout: 180



  # the concrete values for the region are filled in via the prepare kitchen script
  network_ref: # the internal network
    - 74109d28-130d-4500-b806-299026417c2a
  floating_ip_pool: 75ed8d3a-a064-4b81-b4ee-33525cc203cd # the external network
  private_ip_order: 1 # fails with and without this
  # floating_ip:


transport:
  ssh_key: ../os-packer-build-config/id_rsa_kitchen #Path to private key that matches the above openstack key_name
  username: ccloud # For a all images
  connection_timeout: 5
  connection_retries: 10
  server_wait: 60

platforms:
  - name: rhel-7-amd64-vmware-testing
    driver_config:
      image_ref: rhel-7-amd64-vmware-build5
  # - name: linux-redhat7
  #   driver_config:
  #     image_ref: rhel-7-amd64-vmware-build144 # name or id
  # - name: linux-suse12sp1
  #   driver_config:
  #     image_ref: sles-12-sp1-amd64-vmware-build98
  # - name: linux-ubuntu1604
  #   driver_config:
 #      image_ref: ubuntu-16.04-amd64-vmware-build76



suites:
  - name: default
    run_list:
    attributes:
```

The debug log output (slightly anonymized):
```
bash -l -c " source ../os-packer-build-config/region.env &&  kitchen destroy && kitchen create -l debug && kitchen converge -l debug && kitchen setup -l debug && kitchen verify -l debug && kitchen destroy -l debug"
-----> Starting Kitchen (v1.16.0)
-----> Destroying <default-rhel-7-amd64-vmware-testing>...
       OpenStack instance <92931d28-3fd2-455c-879d-9704e41cc55e> destroyed.
       Finished destroying <default-rhel-7-amd64-vmware-testing> (0m0.88s).
-----> Kitchen is finished. (0m1.32s)
-----> Starting Kitchen (v1.16.0)
-----> Creating <default-rhel-7-amd64-vmware-testing>...
D      Selected image: 6a18ea90-8c99-405f-8539-d266cd82f676 rhel-7-amd64-vmware-build5
D      Selected flavor: 20 m1.small
D      Selected net: 74109d28-130d-4500-b806-299026417c2a Private-corp-shared-02
       OpenStack instance with ID of <40bd05e3-578b-4ae8-a48a-2302d490d23b> is ready.
D      Waiting for VM to be in ACTIVE state for a max time of:600 seconds
       Attaching floating IP from <75ed8d3a-a064-4b81-b4ee-33525cc203cd> pool
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Create failed on instance <default-rhel-7-amd64-vmware-testing>.  Please see .kitchen/logs/default-rhel-7-amd64-vmware-testing.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Create failed on instance <default-rhel-7-amd64-vmware-testing>.  Please see .kitchen/logs/default-rhel-7-amd64-vmware-testing.log for more details
D      ----------------------
D      ------Backtrace-------
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:183:in `report_errors'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:174:in `run_action'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/command/action.rb:36:in `block in call'
D      /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/command/action.rb:34:in `call'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:53:in `perform'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:187:in `block (2 levels) in <class:CLI>'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:334:in `invoke_task'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/bin/kitchen:13:in `block in <top (required)>'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/bin/kitchen:13:in `<top (required)>'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/bin/kitchen:23:in `load'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/bin/kitchen:23:in `<main>'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/bin/ruby_executable_hooks:15:in `eval'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/bin/ruby_executable_hooks:15:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::InstanceFailure
D      Message: Create failed on instance <default-rhel-7-amd64-vmware-testing>.  Please see .kitchen/logs/default-rhel-7-amd64-vmware-testing.log for more details
D      ----------------------
D      ------Backtrace-------
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/kitchen-openstack-3.5.0/lib/kitchen/driver/openstack.rb:312:in `block in attach_ip_from_pool'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/kitchen-openstack-3.5.0/lib/kitchen/driver/openstack.rb:298:in `synchronize'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/kitchen-openstack-3.5.0/lib/kitchen/driver/openstack.rb:298:in `attach_ip_from_pool'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/kitchen-openstack-3.5.0/lib/kitchen/driver/openstack.rb:97:in `create'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `public_send'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `block in perform_action'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
D      /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `perform_action'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:370:in `create_action'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:124:in `create'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: No available IPs in pool <75ed8d3a-a064-4b81-b4ee-33525cc203cd>
D      ----------------------
D      ------Backtrace-------
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/kitchen-openstack-3.5.0/lib/kitchen/driver/openstack.rb:312:in `block in attach_ip_from_pool'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/kitchen-openstack-3.5.0/lib/kitchen/driver/openstack.rb:298:in `synchronize'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/kitchen-openstack-3.5.0/lib/kitchen/driver/openstack.rb:298:in `attach_ip_from_pool'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/kitchen-openstack-3.5.0/lib/kitchen/driver/openstack.rb:97:in `create'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `public_send'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `block in perform_action'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
D      /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `perform_action'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:370:in `create_action'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:124:in `create'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
```

If I try the same with `allocate_floating_ip: true` added in the .kitchen.yml I get another error about a undefined method:

```
bash -l -c " source ../os-packer-build-config/region.env &&  kitchen destroy && kitchen create -l debug && kitchen converge -l debug && kitchen setup -l debug && kitchen verify -l debug && kitchen destroy -l debug"
-----> Starting Kitchen (v1.16.0)
-----> Destroying <default-rhel-7-amd64-vmware-testing>...
       Retrieve the floating IP
       OpenStack instance <40bd05e3-578b-4ae8-a48a-2302d490d23b> destroyed.
       Finished destroying <default-rhel-7-amd64-vmware-testing> (0m1.74s).
-----> Kitchen is finished. (0m2.22s)
-----> Starting Kitchen (v1.16.0)
-----> Creating <default-rhel-7-amd64-vmware-testing>...
D      Selected image: 6a18ea90-8c99-405f-8539-d266cd82f676 rhel-7-amd64-vmware-build5
D      Selected flavor: 20 m1.small
D      Selected net: 74109d28-130d-4500-b806-299026417c2a Private-corp-shared-02
       OpenStack instance with ID of <df2a3f49-476a-4cd2-b908-e9754eae45fd> is ready.
D      Waiting for VM to be in ACTIVE state for a max time of:600 seconds
       Attaching floating IP from <75ed8d3a-a064-4b81-b4ee-33525cc203cd> pool
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [undefined method `[]' for nil:NilClass] on default-rhel-7-amd64-vmware-testing
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [undefined method `[]' for nil:NilClass] on default-rhel-7-amd64-vmware-testing
D      ----------------------
D      ------Backtrace-------
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:183:in `report_errors'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:174:in `run_action'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/command/action.rb:36:in `block in call'
D      /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/command/action.rb:34:in `call'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:53:in `perform'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:187:in `block (2 levels) in <class:CLI>'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:334:in `invoke_task'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/bin/kitchen:13:in `block in <top (required)>'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/bin/kitchen:13:in `<top (required)>'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/bin/kitchen:23:in `load'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/bin/kitchen:23:in `<main>'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/bin/ruby_executable_hooks:15:in `eval'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/bin/ruby_executable_hooks:15:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [undefined method `[]' for nil:NilClass] on default-rhel-7-amd64-vmware-testing
D      ----------------------
D      ------Backtrace-------
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/kitchen-openstack-3.5.0/lib/kitchen/driver/openstack.rb:302:in `block in attach_ip_from_pool'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/kitchen-openstack-3.5.0/lib/kitchen/driver/openstack.rb:298:in `synchronize'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/kitchen-openstack-3.5.0/lib/kitchen/driver/openstack.rb:298:in `attach_ip_from_pool'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/kitchen-openstack-3.5.0/lib/kitchen/driver/openstack.rb:97:in `create'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `public_send'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `block in perform_action'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
D      /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `perform_action'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:370:in `create_action'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:124:in `create'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [undefined method `[]' for nil:NilClass]
D      ----------------------
D      ------Backtrace-------
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/kitchen-openstack-3.5.0/lib/kitchen/driver/openstack.rb:302:in `block in attach_ip_from_pool'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/kitchen-openstack-3.5.0/lib/kitchen/driver/openstack.rb:298:in `synchronize'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/kitchen-openstack-3.5.0/lib/kitchen/driver/openstack.rb:298:in `attach_ip_from_pool'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/kitchen-openstack-3.5.0/lib/kitchen/driver/openstack.rb:97:in `create'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `public_send'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `block in perform_action'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
D      /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `perform_action'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:370:in `create_action'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:124:in `create'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /usr/local/rvm/gems/ruby-2.3.1@repository-os-packer/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
```

**Comment by rbabyuk-vs** [comment]
Hi Folks,

I am observing equally the same issue.
kitchen 1.16
kitchen-openstack 3.5.0
any thoughts?
workarounds?

Thanks in advance

**Comment by k0da** [comment]
same issue here

**Comment by B1Sandmann** [comment]
We finally got it to work when using the name of the network instead of the ID. If it's intended to only work with the name it should be better documented.
Example of the relevant config that works for us:
```
  network_ref: # the internal network
    - 74109d28-130d-4500-b806-299026417c2a
  allocate_floating_ip: true 
  floating_ip_pool: FloatingIP-external-project-01 # the external network
``` 

We didn't state a public or private ip order so either the default is okay or it's not relevant. I'm still not quite sure I understand the public/privat_ip_order anyways.

**Comment by jjasghar** [comment]
@B1Sandmann can you put in a PR to make the documentation better? Ideally this will help out @rbabyuk-vs and @k0da too. Thanks!
