### ISSUE TITLE
Openstack  keystone V3, API_URL/v3/auth/tokens  does not work with latest chefdk 3.5.3

### ISSUE THREAD

**Issue by bipinbachhao** [test-kitchen/kitchen-openstack#193]
E, [2018-11-03T14:43:05.086134 #39135] ERROR -- default-redhat: Class: Excon::Error::NotFound
E, [2018-11-03T14:43:05.086156 #39135] ERROR -- default-redhat: Message: Expected([200, 201]) <=> Actual(404 Not Found)
excon.error.response
  :body          => "{\"error\": {\"message\": \"The resource could not be found.\", \"code\": 404, \"title\": \"Not Found\"}}"
  :cookies       => [
  ]
  :headers       => {
    "Content-Length"         => "93"
    "Content-Type"           => "application/json"
    "Date"                   => "Sat, 03 Nov 2018 18:43:05 GMT"
    "Server"                 => "Apache"
    "Vary"                   => "X-Auth-Token"
    "x-openstack-request-id" => "req-457a4119-a265-4f28-a459-f41df4bfaaf2"
  }
  :host          => "openstack....."
  :local_address => "............"
  :local_port    => 50675
  :path          => "/v3/auth/tokens/auth/tokens"
  :port          => 5000
  :reason_phrase => "Not Found"
  :remote_ip     => "........."
  :status        => 404
  :status_line   => "HTTP/1.1 404 Not Found\r\n"

E, [2018-11-03T14:43:05.086178 #39135] ERROR -- default-redhat: ----------------------
E, [2018-11-03T14:43:05.086200 #39135] ERROR -- default-redhat: ------Backtrace-------
E, [2018-11-03T14:43:05.086221 #39135] ERROR -- default-redhat: /Users/c181571/.chefdk/gem/ruby/2.5.0/gems/kitchen-openstack-3.6.2/lib/kitchen/driver/openstack.rb:103:in `rescue in create'
E, [2018-11-03T14:43:05.086244 #39135] ERROR -- default-redhat: /Users/c181571/.chefdk/gem/ruby/2.5.0/gems/kitchen-openstack-3.6.2/lib/kitchen/driver/openstack.rb:76:in `create'

chef gem list

*** LOCAL GEMS ***

activesupport (5.2.1)
addressable (2.5.2)
app_conf (0.4.2)
appbundler (0.11.6)
artifactory (2.8.2)
ast (2.4.0)
aws-sdk (2.11.161)
aws-sdk-core (2.11.161)
aws-sdk-resources (2.11.161)
aws-sigv4 (1.0.3)
axiom-types (0.1.1)
azure_graph_rbac (0.17.0)
azure_mgmt_key_vault (0.17.2)
azure_mgmt_network (0.17.4)
azure_mgmt_resources (0.17.2)
backports (3.11.4)
berkshelf (7.0.6)
bigdecimal (default: 1.3.4)
binding_of_caller (0.8.0)
builder (3.2.3)
bundler (1.16.1)
byebug (10.0.2)
chef (14.6.47)
chef-api (0.8.0)
chef-apply (0.2.2)
chef-config (14.6.47)
chef-dk (3.5.3)
chef-provisioning (2.7.2)
chef-provisioning-aws (3.0.6)
chef-provisioning-fog (0.26.1)
chef-sugar (4.1.0)
chef-telemetry (0.1.0)
chef-vault (3.4.3)
chef-zero (14.0.6)
cheffish (14.0.1)
chefspec (7.3.2)
chefstyle (0.11.0)
citrus (3.0.2)
cleanroom (1.0.0)
cmath (default: 1.0.0)
coderay (1.1.2)
coercible (1.0.0)
concurrent-ruby (1.0.5)
cookbook-omnifetch (0.8.0)
cookstyle (3.0.0)
csv (default: 1.0.0)
cucumber (3.1.2)
cucumber-core (3.2.1)
cucumber-expressions (6.0.1)
cucumber-tag_expressions (1.1.1)
cucumber-wire (0.0.1)
date (default: 1.0.0)
dco (1.0.1)
debug_inspector (0.0.3)
declarative (0.0.10)
declarative-option (0.1.0)
dep-selector-libgecode (1.3.1)
dep_selector (1.0.6)
descendants_tracker (0.0.4)
did_you_mean (1.2.0)
diff-lcs (1.3)
diffy (3.2.1)
docker-api (1.34.2)
domain_name (0.5.20180417)
droplet_kit (2.6.0)
equalizer (0.0.11)
equatable (0.5.0)
erubis (2.7.0)
etc (default: 1.0.0)
excon (0.62.0)
faraday (0.15.3)
faraday-cookie_jar (0.0.6)
faraday_middleware (0.12.2)
fauxhai (6.9.1)
fcntl (default: 1.0.0)
ffi (1.9.25)
ffi-libarchive (0.4.2)
ffi-rzmq (2.0.6)
ffi-rzmq-core (1.0.6)
ffi-yajl (2.3.1)
fiddle (default: 1.0.0)
filesize (0.1.1)
fileutils (default: 1.0.2)
fog-aws (2.0.1)
fog-core (1.45.0)
fog-digitalocean (0.4.0)
fog-joyent (0.0.1)
fog-json (1.2.0)
fog-openstack (0.3.8)
fog-rackspace (0.1.6)
fog-scaleway (0.5.0)
fog-softlayer (1.1.4)
fog-xenserver (1.0.0)
fog-xml (0.1.3)
foodcritic (14.3.0)
formatador (0.2.5)
fuzzyurl (0.9.0)
gcewinpass (1.1.0)
gherkin (5.1.0)
git (1.5.0)
google-api-client (0.23.9)
google-protobuf (3.5.2)
googleauth (0.6.7)
gssapi (1.2.0)
guard (2.14.2)
gyoku (1.3.1)
hashie (3.6.0)
highline (1.7.10)
htmlentities (4.3.4)
http (2.2.2)
http-cookie (1.0.3)
http-form_data (1.0.3)
http_parser.rb (0.6.0)
httpclient (2.8.3)
i18n (1.1.1)
ice_nine (0.11.2)
inifile (3.0.0)
iniparse (1.4.4)
inspec (3.0.25)
io-console (default: 0.4.6)
ipaddr (default: 1.2.0)
ipaddress (0.8.3)
jmespath (1.4.0)
json (default: 2.1.0)
jwt (2.1.0)
kartograph (0.2.7)
kitchen-azurerm (0.14.5)
kitchen-digitalocean (0.10.1)
kitchen-dokken (2.6.7)
kitchen-ec2 (2.3.1)
kitchen-google (2.0.0)
kitchen-hyperv (0.5.2)
kitchen-inspec (0.25.0)
kitchen-openstack (3.6.2)
kitchen-vagrant (1.3.6)
knife-acl (1.0.3)
knife-cloud (1.2.1)
knife-ec2 (0.19.10)
knife-google (3.3.3)
knife-opc (0.4.0)
knife-push (1.0.3)
knife-spork (1.7.2)
knife-tidy (1.2.0)
knife-vsphere (2.1.1)
knife-windows (1.9.6)
libyajl2 (1.2.0)
listen (3.1.5)
little-plugger (1.1.4)
lockfile (2.1.3)
logging (2.2.2)
logify (0.2.0)
lumberjack (1.0.13)
memoist (0.16.0)
method_source (0.9.0)
mime-types (3.2.2)
mime-types-data (3.2018.0812)
mini_portile2 (2.3.0)
minitar (0.7)
minitest (5.11.3, 5.10.3)
mixlib-archive (0.4.18)
mixlib-authentication (2.1.1)
mixlib-cli (1.7.0)
mixlib-config (2.2.13)
mixlib-install (3.11.5)
mixlib-log (2.0.4)
mixlib-shellout (2.4.0)
mixlib-versioning (1.2.2)
molinillo (0.6.6)
ms_rest (0.7.3)
ms_rest_azure (0.11.0)
multi_json (1.13.1)
multi_test (0.1.2)
multipart-post (2.0.0)
nenv (0.3.0)
net-scp (1.2.1)
net-sftp (2.1.2)
net-ssh (4.2.0)
net-ssh-gateway (1.3.0)
net-ssh-multi (1.2.1)
net-telnet (0.1.1)
netaddr (1.5.1)
nokogiri (1.8.5)
nori (2.6.0)
notiffany (0.1.1)
octokit (4.13.0)
ohai (14.6.2)
openssl (default: 2.1.2)
openstack (3.3.20)
opscode-pushy-client (2.4.11)
os (1.0.0)
paint (1.0.1)
parallel (1.12.1)
parser (2.5.3.0)
parslet (1.8.2)
pastel (0.7.2)
plist (3.4.0)
polyglot (0.3.5)
power_assert (1.1.1)
powerpack (0.1.2)
proxifier (1.0.3)
pry (0.11.3)
pry-byebug (3.6.0)
pry-remote (0.1.8)
pry-stack_explorer (0.4.9.2)
psych (default: 3.0.2)
public_suffix (3.0.3)
r18n-core (3.1.2)
r18n-desktop (3.1.2)
rack (2.0.5)
rainbow (3.0.0)
rake (12.3.1, 12.3.0)
rb-fsevent (0.10.3)
rb-inotify (0.9.10)
rb-readline (0.5.5)
rbvmomi (1.13.0)
rdoc (6.0.4, default: 6.0.1)
representable (3.0.4)
resource_kit (0.1.7)
retriable (3.1.2)
retryable (2.0.4)
rspec (3.8.0)
rspec-core (3.8.0)
rspec-expectations (3.8.2)
rspec-its (1.2.0)
rspec-mocks (3.8.0)
rspec-support (3.8.0)
rspec_junit_formatter (0.2.3)
rubocop (0.55.0)
ruby-prof (0.17.0)
ruby-progressbar (1.10.0)
ruby-shadow (2.5.0)
ruby_dep (1.5.0)
rubyntlm (0.6.2)
rubyzip (1.2.2)
rufus-lru (1.1.0)
sawyer (0.8.1)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
semverse (2.0.0)
serverspec (2.41.3)
sfl (2.3)
shellany (0.0.1)
signet (0.11.0)
slop (3.6.0)
solve (4.0.0)
specinfra (2.76.3)
sshkey (1.9.0)
sslshake (1.2.0)
stove (6.0.0)
stringio (default: 0.0.1)
strscan (default: 1.0.0)
syslog-logger (1.6.8)
systemu (2.6.5)
term-ansicolor (1.6.0)
test-kitchen (1.23.2)
test-unit (3.2.7)
thor (0.20.0)
thread_safe (0.3.6)
timeliness (0.3.8)
tins (1.17.0)
toml-rb (1.1.2)
tomlrb (1.2.7)
train (1.5.6)
treetop (1.6.10)
trollop (2.9.9)
tty-color (0.4.3)
tty-cursor (0.6.0)
tty-spinner (0.8.0)
tzinfo (1.2.5)
uber (0.1.0)
ubuntu_ami (0.4.1)
unf (0.1.4)
unf_ext (0.0.7.5)
unicode-display_width (1.4.0)
uuidtools (2.1.5)
virtus (1.0.5)
webrick (default: 1.4.2)
winrm (2.3.0)
winrm-elevated (1.1.0)
winrm-fs (1.3.1)
wmi-lite (1.0.0)
xmlrpc (0.3.0)
yard (0.9.16)
zlib (default: 1.0.0)

Setting openstack_auth_url: <%= "#{ENV['OS_AUTH_URL']}" %> instead of openstack_auth_url: <%= "#{ENV['OS_AUTH_URL']}/auth/tokens" %> works.

fog-openstack changed keystone endpoint after version 0.1.27 

Connection parameters:

@connection_params = {
  openstack_auth_url:     "http://devstack.test:5000/v3/auth/tokens",
  openstack_username:     "admin",
  openstack_api_key:      "password",
  openstack_project_name: "admin",
  openstack_domain_id:    "default"
}

as per kitchen-openstack document V3 no longer works.

**Comment by alex-w-k** [comment]
Yeah, it appends `/auth/tokens` in the newer versions, not sure what's up with that.

**Comment by arielrolfo** [comment]
Facing the same issue here... not able to work with V3

**Comment by ramereth** [comment]
I believe this was fixed in #202 and included in the latest release version. Can you please confirm?
